#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Mapping Curve Test Script
Test open → opose → fist interpolation for specified joints

Usage:
    python3 test_mapping_curve.py [joint_index]
    
    joint_index: 0-20 (sensor index), default: all end joints
    
    Joint mapping:
        2: Thumb Root Flexion
        4: Thumb End Flexion
        6: Index Root Flexion
        8: Index End Flexion
        10: Middle Root Flexion
        12: Middle End Flexion
        14: Ring Root Flexion
        16: Ring End Flexion
        18: Pinky Root Flexion
        20: Pinky End Flexion
    
Example:
    python3 test_mapping_curve.py 6   # Index Root Flexion
    python3 test_mapping_curve.py     # All end joints
"""

import sys
import json
import numpy as np
import pytest
from pathlib import Path

TMP_FILE = Path(__file__).resolve().parent.parent.parent / "linkerhand_retarget" / "motion" / "linkerforce" / "tmp" / "jointangle_data.tmp"
if not TMP_FILE.exists():
    pytest.skip("jointangle_data.tmp is generated by calibration/debug runs", allow_module_level=True)
with open(TMP_FILE) as f:
    data = json.load(f)

open_r = data['jointangleoriginal_r']
opose_r = data['jointangleopose_r']
fist_r = data['jointanglefist_r']

JOINT_NAMES = {
    2: '拇指根部', 4: '拇指末端',
    6: '食指根部', 8: '食指末端',
    10: '中指根部', 12: '中指末端',
    14: '无名指根部', 16: '无名指末端',
    18: '小指根部', 20: '小指末端',
}

EXP_FACTORS = {
    2: 5, 4: 7,
    6: 10, 8: 3,
    10: 5, 12: 10,
    14: 5, 16: 18,
    18: 5, 20: 8,
}

MOTOR_OPEN = 255
MOTOR_OPOSE = 128
MOTOR_FIST = 0

def interpolate(a, b, t):
    return a + (b - a) * t

def map_value(sensor_val, sensor_open, sensor_opose, sensor_fist, exp_factor):
    if abs(sensor_opose - sensor_open) < 1e-6:
        normalized = 0.5
    else:
        normalized = (sensor_val - sensor_open) / (sensor_opose - sensor_open)
    
    if normalized <= 0:
        return MOTOR_OPEN, normalized
    elif normalized <= 1:
        return MOTOR_OPEN + normalized * (MOTOR_OPOSE - MOTOR_OPEN), normalized
    else:
        exceed_amount = normalized - 1.0
        slope = MOTOR_FIST - MOTOR_OPOSE
        if exp_factor == 1.0:
            extension = exceed_amount * slope
        else:
            linear_extension = exceed_amount * slope
            exp_multiplier = 1.0 + (exp_factor - 1.0) * exceed_amount
            extension = linear_extension * exp_multiplier
        result = MOTOR_OPOSE + extension
        return max(MOTOR_FIST, result), normalized

def print_joint_curve(idx):
    name = JOINT_NAMES.get(idx, f'关节{idx}')
    exp_factor = EXP_FACTORS.get(idx, 5)
    
    sensor_open = open_r[idx]
    sensor_opose = opose_r[idx]
    sensor_fist = fist_r[idx]
    
    normalized_fist = (sensor_fist - sensor_open) / (sensor_opose - sensor_open) if abs(sensor_opose - sensor_open) > 1e-6 else 0.5
    
    print(f"【{name}】 (传感器索引 {idx}, exp_factor={exp_factor})")
    print("-" * 75)
    print(f"传感器值: open={sensor_open:.4f}, opose={sensor_opose:.4f}, fist={sensor_fist:.4f}")
    print(f"normalized_fist={normalized_fist:.4f}")
    print()
    print(f"{'阶段':<12} {'插值t':<8} {'传感器值':<12} {'normalized':<12} {'电机值':<10} {'说明'}")
    print("-" * 75)
    
    for t in np.arange(0, 1.1, 0.1):
        sensor_val = interpolate(sensor_open, sensor_opose, t)
        motor_val, normalized = map_value(sensor_val, sensor_open, sensor_opose, sensor_fist, exp_factor)
        print(f"open→opose  {t:<8.1f} {sensor_val:<12.4f} {normalized:<12.4f} {motor_val:<10.1f}")
    
    print()
    
    for t in np.arange(0, 1.1, 0.1):
        sensor_val = interpolate(sensor_opose, sensor_fist, t)
        motor_val, normalized = map_value(sensor_val, sensor_open, sensor_opose, sensor_fist, exp_factor)
        phase = "延伸" if t > 0 else "opose"
        print(f"opose→fist  {t:<8.1f} {sensor_val:<12.4f} {normalized:<12.4f} {motor_val:<10.1f} {phase}")
    
    print()

def main():
    if len(sys.argv) > 1:
        try:
            idx = int(sys.argv[1])
            if idx not in JOINT_NAMES:
                print(f"错误: 不支持关节索引 {idx}")
                print("有效索引:", sorted(JOINT_NAMES.keys()))
                return
            print("=" * 80)
            print(f"映射曲线测试 - 关节 {idx}")
            print("=" * 80)
            print()
            print_joint_curve(idx)
        except ValueError:
            print(__doc__)
    else:
        print("=" * 80)
        print("映射曲线测试 - 所有末端关节")
        print("=" * 80)
        print()
        for idx in [4, 8, 12, 16, 20]:
            print_joint_curve(idx)
    
    print("=" * 80)
    print("测试完成")
    print("=" * 80)

if __name__ == "__main__":
    main()
